// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srrgjyathvxhlzjkpeop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNycmdqeWF0aHZ4aGx6amtwZW9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MTY3MDIsImV4cCI6MjA1ODQ5MjcwMn0.vSYINidCa4NJgJY5q8nqrBxSbbuUeoX1UNXRSxRaduI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);